### ISSUE TITLE
Error: Missing stack name; for test mode, please call `pulumi.runtime.setMocks` and provide a `stack` argument (NODEJS  - TYPESCRIPT)

### ISSUE THREAD

**Issue by pedrofreit4s** [pulumi/pulumi-libvirt#43]
### What happened?

Hello, unfortunately I am not able to use this package. I'm having errors.

` const d = await lib.Network.get("default", "f5cd7f9e-5fb9-44b1-9d97-98019db8db9b");`

Output:

`<ref *1> Error: Missing stack name; for test mode, please call `pulumi.runtime.setMocks` and provide a `stack` argument
    at Object.getStack (/home/pedrofreitas/www/introti/api.introti.com/node_modules/@pulumi/runtime/settings.ts:188:11)
    at Object.createUrn (/home/pedrofreitas/www/introti/api.introti.com/node_modules/@pulumi/resource.ts:49:54)
    at Object.<anonymous> (/home/pedrofreitas/www/introti/api.introti.com/node_modules/@pulumi/runtime/resource.ts:253:43)
    at Generator.next (<anonymous>)
    at /home/pedrofreitas/www/introti/api.introti.com/node_modules/@pulumi/pulumi/runtime/resource.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (/home/pedrofreitas/www/introti/api.introti.com/node_modules/@pulumi/pulumi/runtime/resource.js:17:12)
    at /home/pedrofreitas/www/introti/api.introti.com/node_modules/@pulumi/runtime/resource.ts:226:48
    at /home/pedrofreitas/www/introti/api.introti.com/node_modules/@pulumi/runtime/resource.ts:862:16
    at Generator.next (<anonymous>) {
  promise: Promise { <rejected> [Circular *1] }`

### Steps to reproduce

I installed the package, and imported
`  import * as lib from "@pulumi/libvirt";`

### Expected Behavior

I expected you to bring me my network data

### Actual Behavior

He showed me the strangers that I couldn't solve

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
Since we haven't heard back, I'll go ahead and close this issue as stale. Based on the error message, I _think_ you were trying to run your program outside the Pulumi CLI context.

Please open a new issue if the problem still persists and provide the details for us to reproduce it. Thank you!
